### ISSUE TITLE
部署成功，调用报错

### ISSUE THREAD

**Issue by onion0835** [SmileSmith/chatgpt-proxy#1]
部署成功，调用报错
![image](https://user-images.githubusercontent.com/24467503/228097034-f5aa6192-bcbb-4a44-b6c7-7bc9ee9d67cb.png)

**Comment by mayan368** [comment]
我收到是一个字一个字的返回，怎么改成只返回一句话呢？
![image](https://user-images.githubusercontent.com/24467503/228118175-ea8eed1d-cdef-45e5-a808-6b284cdc338c.png)

**Comment by SmileSmith** [comment]
> 我收到是一个字一个字的返回，怎么改成只返回一句话呢？ ![image](https://user-images.githubusercontent.com/24467503/228118175-ea8eed1d-cdef-45e5-a808-6b284cdc338c.png)

这个项目还不支持配置一次性返回数据，我加个参数配置吧。

一个字一个字返回，是参考openai故意这样实现的，官方的接口默认也是stream流式的，可搜索关键字 SSE（Server Sent Event）。官方这么设计，原因是chatgpt本质上是一个文字接龙的函数，每次都接收前面的字符，计算下一个字符。

个人建议还是使用sse，复合chatgpt运行原理，用户也能更快看到第一个字符响应。

**Comment by onion0835** [comment]
好的，谢谢大佬

**Comment by SmileSmith** [comment]
可以拉代码，重新部署后试试加上noStreaming
`curl http://localhost:8000/api/conversation -H "Content-Type: application/json" -d  "{\"message\": \"Hoello\",\"noStreaming \":1}"`
